version: "3.8"

services:
  metasploitable2:
    image: tleemc2/metasploitable2
    container_name: metasploitable2
    restart: unless-stopped
    networks:
      - NETWORKPAULO
    ports:
      - "2121:21"        # host 2121 -> container 21 (FTP)

  decoy_nginx:
    image: nginx:stable-alpine
    container_name: decoy_nginx
    restart: unless-stopped
    networks:
      - NETWORKPAULO
    ports:
      - "2431:80"        # host 2431 -> container 80 (HTTP)

  decoy_postgres:
    image: postgres:15
    container_name: decoy_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=decoy
      - POSTGRES_PASSWORD=decoypassword
    networks:
      - NETWORKPAULO
    ports:
      - "3333:5432"      # host 3333 -> container 5432 (Postgres)

networks:
  NETWORKPAULO:
    driver: bridge
    name: NETWORKPAULO